### ISSUE TITLE
Missing version git tags

### ISSUE THREAD

**Issue by kloczek** [tk0miya/docutils-stubs#35]
Yeah .. looks like there is no any git version tags in repo.

**Comment by tk0miya** [comment]
done.

**Comment by kloczek** [comment]
Looks like again git tag is missing :)
This time for 0.0.21.

**Comment by McSinyx** [comment]
0.0.21 is not present in this repo, but IIRC it was basically cd0fc0a45d6afec9db66e770ff7257154cb58cd0 on top of 0.0.20 content-wise.
