### ISSUE TITLE
Licence claryfication

### ISSUE THREAD

**Issue by kloczek** [tk0miya/docutils-stubs#36]
I cannot find in the code any traces of data under what kind of license is provided docutils-stubs.
```
[tkloczko@barrel docutils-stubs-0.0.21]$ grep Lice PKG-INFO
License: UNKNOWN
```

**Comment by tk0miya** [comment]
Now we added a LICENSE file at https://github.com/tk0miya/docutils-stubs/pull/34.
Is this resolved? If not, could you send a PR please?

**Comment by kloczek** [comment]
Issue is that generated PKG-INFO has missing license info.

**Comment by tk0miya** [comment]
What should we do?

**Comment by kloczek** [comment]
Looks like docutils-stubsdocutils-stubs is provided under MIT license so in setup.cfg is missing:
```
[metadata]
license = MIT
```
